version: '3'
services:
    elasticsearch:
        image: "elastic_store"
        ports:
            - "9200:9200"
        environment: 
            - ELASTIC_PASSWORD=password
            - xpack.security.enabled=true
        network_mode: bridge